parameters:
#    taller2012_base.example.class: Taller2012\BaseBundle\Example

services:
#    taller2012_base.example:
#        class: %taller2012_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
